name: Release Node.js SDK
run-name: Release Node.js SDK

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    name: Publish NPM
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          registry-url: https://registry.npmjs.org

      - run: npm ci

      - name: Set NPM version from tag
        run: npm version ${GITHUB_REF_NAME#v} --allow-same-version --no-git-tag-version

      - run: npm run build

      - name: Publish to NPM
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
